### ISSUE TITLE
Ask for adding callback on quickstart download [CLI-59]

### ISSUE THREAD

**Issue by woloski** [auth0/auth0-cli#128]
Once quickstart is download before finishing ask `Do you want to add this URL to the list of allowed callback URLs: http://localhost:3000?`

**Comment by Widcket** [comment]
Good idea, but only for web apps and SPAs, as in mobile custom schemes are used.

**Comment by Widcket** [comment]
Added the card [CLI-59](https://auth0team.atlassian.net/browse/CLI-59) to track this.

**Comment by Widcket** [comment]
Describing this task as:

Once a quickstart has finished downloading, before finishing:

- If the app is a **SPA**, ask:
  - `Do you want to add this URL to the list of allowed callback URLs: http://localhost:3000?`
  - `Do you want to add this URL to the list of allowed logout URLs: http://localhost:3000?`
  - `Do you want to add this URL to the list of allowed web origins: http://localhost:3000?`

- If the app is a **Regular Web App**, ask:
  - `Do you want to add this URL to the list of allowed callback URLs: http://localhost:3000?`
  - `Do you want to add this URL to the list of allowed logout URLs: http://localhost:3000?`

Because all those are needed (with those values) to get the app running.

**Comment by woloski** [comment]
can we do this one?

**Comment by Widcket** [comment]
Sure, I just picked up the card.

**Comment by Widcket** [comment]
The card is already picked up and on the "In Progress" lane.

**Comment by aherzog-auth0** [comment]
@Widcket I started a draft for it but I need to run right now. Feel free to continue off my draft, otherwise I will complete it over the weekend or early next week. 

Needs a check for if the urls already exist (will throw an error if they do) and tests.

**Comment by Widcket** [comment]
Implemented in https://github.com/auth0/auth0-cli/pull/155.
