### ISSUE TITLE
Feature Request: auth0 tenants create

### ISSUE THREAD

**Issue by mathiasconradt** [auth0/auth0-cli#256]
### Describe the problem you'd like to have solved

Allow to create Auth0 tenants programmatically / via API & CLI. 
Right now, it's only possible via Auth0 UI/Dashboard.

### Describe the ideal solution

`auth0 tenants create`

Parameters:
tenant name
tenant region

## Alternatives and current work-arounds

Using RPA
https://github.com/mathiasconradt/auth0-tenant-creation-rpa

### Additional context

This is useful for B2B2X scenarios and has been requested a few times in the past.

**Comment by Widcket** [comment]
Hi @mathiasconradt,

Thanks for raising this. Currently the Auth0 CLI is just a thin client for the Management API, and therefore is limited to the operations that can be performed through the API. However, I've recorded this feature request in an internal document, so that we can implement this whenever it becomes possible.
Since we can't act on this feature request in the short term, I'll close this issue, but it remains referenced in that internal document.

**Comment by lbowe** [comment]
+1 for this ability in the API/CLI
