### ISSUE TITLE
auth0 cli ignores the --audience parameter when generating an access token

### ISSUE THREAD

**Issue by AndrewRayCode** [auth0/auth0-cli#344]
### Description

`--audience` is not used in the resulting token from `auth0 test login`

### Reproduction

I'm trying to run a command to get a user berare token to test with automatically:

```
auth0 test login MY_CLIENT_ID --no-input --force --domain MY_DOMAIN --audience myaudience
```

With this flow, I'm taken to my staging login page, I auth with a staging user, then I get a token successfully on my clipboard. However, when I paste this token into https://jwt.io/ it has the wrong audience:

```
"aud": "MY_CLIENT_ID",
```

For some reason it used the client ID instead of the audience passed in to the CLI for the bearer token returned

### Environment

- **Version of this library used:**
auth0 --version
auth0 version 0.6.0 b69b35ae1f74e6b0caa1d96392fc575ffc0fafd8

- **Version of the platform or framework used, if applicable:**
Mac Big Sur, iTerm2

**Comment by Widcket** [comment]
Hi @AndrewRayCode,
I just tried this command and the Access Token contains 2 audience values: the `userinfo` endpoint and the value passed via flag:

<img width="405" alt="Screen Shot 2021-08-03 at 22 46 12" src="https://user-images.githubusercontent.com/5055789/128109046-756aaf66-4818-4b8a-b1df-aba7ba69aad1.png">

The ID Token, on the other hand, contains a single audience value which is the Client ID:

<img width="371" alt="Screen Shot 2021-08-03 at 22 47 34" src="https://user-images.githubusercontent.com/5055789/128109059-ac893d92-f959-4aa8-8ddb-6318fd72e436.png">

This is due to the ID Token having a different purpose than the Access Token. The first is meant to be consumed by the app, hence the app ID (the Client ID) being its audience value. The latter is meant to be consumed by an API, hence the audience value containing the API identifier.

I'll close this issue, please ping if you'd like to reopen.
