### ISSUE TITLE
"auth0 logs" --format option seems to do nothing

### ISSUE THREAD

**Issue by joshw** [auth0/auth0-cli#419]
### Description

When using `auth0 logs tail`, I found that the displayed data was not as I wished (see https://github.com/auth0/auth0-cli/issues/418)   I had hoped to work around this with the `--format json` option mentioned in the help, but it doesn't appear to do anything- the output is still text, in the standard format.

### Reproduction

```
auth0 logs tail --format json
```

I would expect this to output data in json format.

### Environment

> Please provide the following:

- **Version of this library used:**
```
% auth0 --version
auth0 version 0.11.7 f9bcaf1b0d5c6c380022842b9707dfb8620b4890
```

- **Version of the platform or framework used, if applicable:**
n/a

- **Other relevant versions (language, server software, OS, browser):**

```
Darwin  20.6.0 Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64 x86_64
```

- **Other modules/plugins/libraries that might be involved:**
n/a

**Comment by willvedd** [comment]
@joshw Thanks for the suggestion. I agree that the `--format` flag is effectively useless in this situation. But how would you expect the tailing output to be constructed in JSON? Would you just want a continually growing array of log entries? I'm unable to imagine how that would be useful though.

What is your usecase for wanting the output in a different format? What are you trying to achieve here? Maybe that's a better starting point, so then we can figure out possibly a better solution for you.

**Comment by willvedd** [comment]
**Update:** We've removed the `--format` flag from `auth0 logs tail` in the [v1.0.0-beta.1](https://github.com/auth0/auth0-cli/releases/tag/v1.0.0-beta.1) release. It didn't make sense to try and figure out a way to print out JSON without a clear use case. And if a reasonable solution is proposed, we can always add-in later.

For those who are so inclined, we'd be happy to receive feedback on the beta before it goes GA, including feedback on this particular issue. Otherwise, we plan to close this issue out once v1.0.0 reaches GA.

**Comment by willvedd** [comment]
The `--format` flag has indeed been removed from `auth0 logs tail` in the [v1.0.0](https://github.com/auth0/auth0-cli/releases/tag/v1.0.0) release. We don't think it makes sense to have JSON output for tail'ing at this time when `auth0 logs list --json` is an adequate replacement.
