### ISSUE TITLE
Storybook not starting when updating the UL

### ISSUE THREAD

**Issue by ambravo** [auth0/auth0-cli#642]
I have the same issue reported here: https://github.com/auth0/auth0-cli/issues/638#issuecomment-1416533889 by @jsw

---------
              Happy to report this elsewhere, but  I ran into the same issue, downloaded 1.0.0-beta.1, but when I run `./auth0 universal-login templates update` I get the editor in my console but no browser window as expected in these docs

https://auth0.com/docs/customize/universal-login-pages/universal-login-page-templates#using-the-auth0-cli

_Originally posted by @jsw in https://github.com/auth0/auth0-cli/issues/638#issuecomment-1416533889_

**Comment by willvedd** [comment]
We had previously removed the storybook functionality from v1 because of the perceived maintenance burden and complexity, but upon further review, we've decided to add back in. It's included in the [v1.0.0-beta.3](https://github.com/auth0/auth0-cli/releases/tag/v1.0.0-beta.3) release. We ask that you give it a go! Thanks for your feedback.
